# Generated by Django 2.2.17 on 2021-02-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_auto_20210211_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.URLField(default=0),
        ),
    ]
